### ISSUE TITLE
Dash rather than asterisk used for unordered lists

### ISSUE THREAD

**Issue by daniel-sim** [jpuri/draftjs-to-markdown#3]
I'm having an issue using the markdown generated because it uses a dash rather than an asterisk for unordered lists.

Of course, markdown isn't a specification, but it seems like asterisk is the most common.

**Comment by daniel-sim** [comment]
@jpuri any ideas about a solution for this?

**Comment by jpuri** [comment]
Hey @daniel-sim: I think it would be nice to give user option to pass a config object to change the character used.

I will be happy to have a PR for it, I am more occupied atm but I will do this change as I as soon as I get time.

**Comment by daniel-sim** [comment]
@jpuri How about I modify ```draftToMarkdown``` to take an optional ```blockTypesMapping``` that will merge with ```const blockTypesMapping```?

**Comment by jpuri** [comment]
It will be nicer to have it more generic like 
```
{
  blockTypesMapping : {/**mappings*/},
}
```
Thus in future more config parameters can be added to the object.

**Comment by daniel-sim** [comment]
So ```draftToMarkdown(contentState, hashConfig, customEntityTransform, config)```

Where config is

```
{
  blockTypesMapping : {/**mappings*/},
}
```

**Comment by jpuri** [comment]
Looks good !
