### ISSUE TITLE
extra console.logs

### ISSUE THREAD

**Issue by marbemac** [jpuri/draftjs-to-markdown#7]
Popped up in the last release:

https://github.com/jpuri/draftjs-to-markdown/blob/9b7ffccd13c8a56e12bb327fad2a79776968a4b2/js/index.js#L554-L555

**Comment by jpuri** [comment]
Ops my bad, I will fix it soon. Thx for reporting.

**Comment by jpuri** [comment]
Just published `draftjs-to-markdown@0.4.2` with the fix.
