### ISSUE TITLE
Images output format is incomplete

### ISSUE THREAD

**Issue by eduludi** [jpuri/draftjs-to-markdown#9]
Looks like `!(src)` is not a valid Markdown image format. I wasn't able to find any example using this format and parsers don't accept it, like `react-markdown`. 

The format should be: `![](src)`

Test:
![screen shot 2017-06-29 at 09 46 36](https://user-images.githubusercontent.com/76132/27676884-fb86c856-5caf-11e7-95e3-74e52e3e377b.png)

And after adding `[]`: 
![screen shot 2017-06-29 at 09 47 25](https://user-images.githubusercontent.com/76132/27676890-004770c0-5cb0-11e7-8e76-d1dd8feee817.png)

Btw, thanks for this library!

**Comment by jpuri** [comment]
@eduludi : I am looking into this.

**Comment by jpuri** [comment]
I have change image markdown and square brackets will have alt text if present in the image.

Release `draftjs-to-markdown@0.4.3`

Thanks
